import Head from 'next/head'
import Image from 'next/image'
import { Text } from '@chakra-ui/react'
import pic from '../public/mammoth-camping.jpeg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Will Naugle # Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ width: '100%' }}>
        <Image src={pic} alt="Deer Lakes, Mammoth CA" />
      </div>
    </>
  )
}
